import type { Metadata } from 'next'
import './globals.css'
import { ModeToggle } from '@/components/mode-toggle'
import { cn } from '@/lib/utils'
import { Providers } from './provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn('h-full', 'antialiased', 'font-sans')}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <div>
            <ModeToggle />
          </div>
          {children}
        </Providers>
      </body>
    </html>
  )
}
